### ISSUE TITLE
python setup.py报错

### ISSUE THREAD

**Issue by yuhua666** [ggjy/DeFeat.pytorch#27]
Traceback (most recent call last):
  File "setup.py", line 195, in <module>
    write_version_py()
  File "setup.py", line 71, in write_version_py
    sha = get_hash()
  File "setup.py", line 56, in get_hash
    raise ImportError('Unable to get git version')
ImportError: Unable to get git version

**Comment by yuhua666** [comment]
现在的报错是：
RuntimeError: Error compiling objects for extension

**Comment by yuhua666** [comment]
expected str, bytes or os.PathLike object, not NoneType
